name: Build Xiaomi Mi 8 Pro or Explorer Edition
on:
  workflow_dispatch:
  schedule:
      # Run once at 12:00 on Saturday. See http://crontab.guru
      - cron: '00 12 * * 6'
  push:
    branches:
      - HEAD
  pull_request:
      branches:
      - HEAD

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_MAXSIZE: "2G"
      CCACHE_HARDLINK: "true"
      KERNEL_CMDLINE: "ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- O=out"
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 100

    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Install dependencies
      run: |
        sudo apt-get update -y 
        sudo apt install binutils make python2 python libssl-dev flex unzip libssl-dev ca-certificates xz-utils mkbootimg cpio device-tree-compiler git git-lfs bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev adb fastboot -y
        git clone https://github.com/Coconutat/ToolChains.git --dept=1 -b linaro_gcc_5.5
        make mrproper
    
    - name: GetTime
      id: get_time
      run: |
        echo "TIME=$(TZ=UTC-8 date +%m%d%H%M )" >> $GITHUB_OUTPUT
    
    - name: Clean
      run: |
        make clean
        make mrproper

    - name: Build Kernel
      run: |
       rm -rf KernelSU
       rm -rf drivers/kernelsu
       curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
       export PATH=$(pwd)/ToolChains/bin/:$PATH
       export ARCH=arm64
       export SUBARCH=arm64
       export CONFIG_BUILD_ARM64_DT_OVERLAY=y
       export DTC_EXT=dtc
       make $KERNEL_CMDLINE generic_xiaomi_sdm845_ksu_defconfig
       make $KERNEL_CMDLINE -j$(nproc --all)
       cp out/arch/arm64/boot/Image.gz tools/AnyKernel3/Image.gz
       cp out/arch/arm64/boot/Image.gz-dtb tools/AnyKernel3/Image.gz-dtb
       cp -vf tools/AnyKernel3_sh/anykernel.sh tools/AnyKernel3/
       cp -vf tools/AnyKernel3_sh/banner tools/AnyKernel3/
       

    - name: Upload KSU-Kernel
      uses: actions/upload-artifact@v3
      with:
        name: Mi8_sdm845-generic_MIUI_12.5_Kernel-${{ steps.get_time.outputs.TIME }}
        path: "tools/AnyKernel3/*"
